### ISSUE TITLE
Backend: Merge Service not merging and not minding

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaMergingService#2]
if i make this request:
`curl -X POST -H "Content-type: application/json" -d '{"studyId":"PRISM0002-1","filters":[],"entityId":"EUPATH_0000738","outputVariables":[{"entityId":"EUPATH_0000738","variableId":"EUPATH_0000338"},{"entityId":"EUPATH_0000738","variableId":"IAO_0000414"},{"entityId":"EUPATH_0000096","variableId":"EUPATH_0000150"}],"derivedVariables":[]}' http://localhost:8083/query`

i see an error in the merge service:
`Caused by: java.lang.RuntimeException: Ancestor stream 'EUPATH_0000096' could not provide a row matching 'EUPATH_0000096.Participant_stable_id' with value '3001'.`

interestingly, the data service doesnt seem to mind and just continues along w whatever data its received.

**Comment by ryanrdoherty** [comment]
Fixed.  I had inadvertently turned off sorting by defaulting to the wide table lookup.
