### ISSUE TITLE
Backend: Request with no variables returns an extra column with no header

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/EdaMergingService#6]
I'm running the merging service locally with eda-local-backend and am hooked up to rm41910.

When testing the ranked abundance app, I observed the following behavior:

If I send this to the merging service:
```
{"studyId":"Ciara_V1V3-1","filters":[],"entityId":"EUPATH_0000809","outputVariables":[],"derivedVariables":[]}
```

I receive back 4 columns of data, but only 3 headers. (Raw data is in the top, raw data pasted into excel to more easily see the columns in bottom)

<img width="1459" alt="Screen Shot 2022-03-11 at 1 10 59 PM" src="https://user-images.githubusercontent.com/11710234/157925492-9f554221-68cd-40ec-9eaf-60cbe90d2737.png">

Is this the expected behavior? 

I would expect this sort of request is uncommon because it has no variables. I came across this situation when testing the ranked abundance box plot backend. With no overlays or facets, the ranked abundance computation provides the x and y vars, so the visualization request actually has no variables. If i add an overlay or facet var to my ranked abundance boxplot request, all works as expected.

**Comment by ryanrdoherty** [comment]
@asizemore This is now fixed in dev.  I'll push out a new version to QA tomorrow after the demo.

**Comment by ryanrdoherty** [comment]
This was fixed long ago but never got closed.  Closing now (also retested with new DV logic and still fixed).
